### ISSUE TITLE
Add lock/unlock report dir command

### ISSUE THREAD

**Issue by nrdg42** [awslabs/aws-build-accumulator#100]
`litani print-capabilities -r` shows that Litani has a Lockable Directory API in `lib.litani`. As a Litani user, I want a litani command that enables me to make use of that functionality take a lock on and release Litani's Report directory during a run.

### Acceptance
* top level commands to lock and release the report directory
* e2e tests
* Man page
* Add to litani capabilities

**Comment by karkhaz** [comment]
This was fixed in 9116fb9 and released in 1.4.0.
