### ISSUE TITLE
Create `litani dump-jobs`

### ISSUE THREAD

**Issue by karkhaz** [awslabs/aws-build-accumulator#107]
Analagous to `litani dump-run`, it should print a list of jobs to stdout.

Acceptance:
- Implement the command
- It should also have a `-o`/`--out-file` flag to write the list of jobs to a file instead of stdout, some people prefer that to a redirection
- Write a man page, it will probably be similar to dump-run

**Comment by ronakfof** [comment]
With this command, do you just expect the `jobs` list from the `run` output of `dump-run`?

**Comment by karkhaz** [comment]
Fixed in #130
