### ISSUE TITLE
Add an option to compare two (or more) runs

### ISSUE THREAD

**Issue by celinval** [awslabs/aws-build-accumulator#51]
It would be amazing if we could compare the results for two different runs by entering a code commit id, a date or even run id. Ideally, users could see the results side by side. Let's say the table with the runs would have duplicated columns per run. Any graph would include the runs being compared.

Furthermore, we could also generate a json with a summary of the difference. The .json could be used to automate tests that compare a PR run against a stable run.

**Comment by tautschnig** [comment]
I could be wrong, but I thought @markrtuttle has at least built a tool to compare the .json reports.

**Comment by markrtuttle** [comment]
I am implementing something like this for viewer regression.  If you look at my branch [testing-with-broken-http](https://github.com/markrtuttle/aws-viewer-for-cbmc/tree/testing-with-broken-http), you can see the beginning of this in tests and tests/coreHTTP.  I am actively working on viewer regression, so let's not duplicate too much.

**Comment by karkhaz** [comment]
This is out of scope for Litani, but we're working on a similar tool now.

**Comment by karkhaz** [comment]
This is out of scope for Litani, but we're working on a similar tool now.
