### ISSUE TITLE
Allow users to specify an output directory for the Litani test suite

### ISSUE THREAD

**Issue by karkhaz** [awslabs/aws-build-accumulator#74]
Currently, the Litani test suite writes its output to a file within the source directory, which is .gitignored. However, if the source directory has been installed in a root-owned location using a package manager, then running the tests will fail as it will not be possible to write the test directory.

Acceptance:
The `test/run` script should accept an optional directory as a command line argument. The test suite should not write any file outside that directory.

**Comment by angelonakos** [comment]
Addressed by @ronakfof in #78
